name: release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22' # The Go version to download (if necessary) and use.
      - run: go version
      - run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o echo-server .
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: echo-server
          path: ./echo-server

  release:
    name: Release artifacts
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Publish release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          name: "Release ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            **/echo-server